#!/bin/bash

NAME="jbs_system"                                 # Name of the application
DJANGODIR=/Progects/JobSoamer/jbs_system             # Django project directory
SOCKFILE=/Progects/JobSoamer/jbs_system/run/gunicorn.sock  # we will communicte using this unix socket
USER=user                                        # the user to run as                                    # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=jbs_system.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=jbs_system.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
# shellcheck disable=SC2164
cd $DJANGODIR
source venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-