# Generated by Django 3.2.2 on 2021-05-27 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='file_mailing',
            field=models.FileField(upload_to='files_mailing', validators=[django.core.validators.FileExtensionValidator(['docx', 'doc', 'rtf', 'txt', 'pdf'], message='wrong file extension')]),
        ),
    ]
