# Generated by Django 3.2.2 on 2021-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0005_auto_20210531_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='alias',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
