# Generated by Django 3.2.2 on 2021-05-31 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0006_alter_portal_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('cv_data', models.CharField(max_length=500)),
                ('cv_file_name', models.CharField(max_length=500)),
                ('ai_resume_builder', models.BooleanField(default=False)),
                ('dropbox_cv_url', models.CharField(blank=True, default='', max_length=500)),
                ('upload_file', models.FileField(upload_to='files_test', validators=[django.core.validators.FileExtensionValidator(['docx', 'doc', 'rtf', 'txt', 'pdf'], message='wrong file extension')])),
                ('copy_paste', models.CharField(max_length=500)),
                ('authenticity_token', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
