# Generated by Django 3.2.2 on 2021-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0007_testdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='authenticity_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='copy_paste',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='cv_data',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='cv_file_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='email',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='firstname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='lastname',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
