# Generated by Django 3.2.2 on 2021-06-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0008_auto_20210531_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_proxy', models.CharField(blank=True, default='', max_length=500)),
                ('host_proxy', models.CharField(blank=True, default='', max_length=500)),
                ('port_proxy', models.SmallIntegerField(blank=True, default=0)),
                ('username_proxy', models.CharField(blank=True, default='', max_length=500)),
                ('password_proxy', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
