# Generated by Django 3.2.2 on 2021-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsystem', '0013_alter_order_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='login',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
